RateMyTechship/Controllers/BlogsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using RateMyTechship.Data;
using RateMyTechship.Models;

namespace RateMyTechship.Controllers
{
    public class BlogsController : Controller
    {
        private readonly ApplicationDbContext _context;

        public BlogsController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: Blogs
        public async Task<IActionResult> Index()
        {
            return View(await _context.Blog.ToListAsync());
        }

        // GET: Blogs/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var blog = await _context.Blog
                .FirstOrDefaultAsync(m => m.Id == id);
            if (blog == null)
            {
                return NotFound();
            }

            return View(blog);
        }

        [Authorize(Roles = "Admin")]
        // GET: Blogs/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Blogs/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Title,Author,Major,Date,Content,BackgroundImage")] Blog blog)
        {
            if (ModelState.IsValid)
            {
                _context.Add(blog);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(blog);
        }

        [Authorize(Roles = "Admin")]
        // GET: Blogs/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var blog = await _context.Blog.FindAsync(id);
            if (blog == null)
            {
                return NotFound();
            }
            return View(blog);
        }

        // POST: Blogs/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Title,Author,Major,Date,Content,BackgroundImage")] Blog blog)
        {
            if (id != blog.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    // Retrieve the existing blog from the database
                    var existingBlog = await _context.Blog.FindAsync(id);

                    // Update the properties of the existing blog with the values from the edited blog
                    existingBlog.Title = blog.Title;
                    existingBlog.Author = blog.Author;
                    existingBlog.Major = blog.Major;
                    existingBlog.Date = blog.Date;
                    existingBlog.Content = blog.Content;
                    existingBlog.BackgroundImage = blog.BackgroundImage;

                    // Update the blog in the database
                    _context.Update(existingBlog);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!BlogExists(blog.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(blog);
        }

        // POST: Blogs/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        //[HttpPost]
        //[ValidateAntiForgeryToken]
        //public async Task<IActionResult> Edit(int id, [Bind("Id,Title,Author,Major,Date,Content")] Blog blog)
        //{
        //    if (id != blog.Id)
        //    {
        //        return NotFound();
        //    }

        //    if (ModelState.IsValid)
        //    {
        //        try
        //        {
        //            _context.Update(blog);
        //            await _context.SaveChangesAsync();
        //        }
        //        catch (DbUpdateConcurrencyException)
        //        {
        //            if (!BlogExists(blog.Id))
        //            {
        //                return NotFound();
        //            }
        //            else
        //            {
        //                throw;
        //            }
        //        }
        //        return RedirectToAction(nameof(Index));
        //    }
        //    return View(blog);
        //}

        [Authorize(Roles = "Admin")]
        // GET: Blogs/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var blog = await _context.Blog
                .FirstOrDefaultAsync(m => m.Id == id);
            if (blog == null)
            {
                return NotFound();
            }

            return View(blog);
        }

        [Authorize(Roles = "Admin")]
        // POST: Blogs/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var blog = await _context.Blog.FindAsync(id);
            if (blog != null)
            {
                _context.Blog.Remove(blog);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool BlogExists(int id)
        {
            return _context.Blog.Any(e => e.Id == id);
        }
    }
}

RateMyTechship/Controllers/ReviewsController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Hosting;
using RateMyTechship.Data;
using RateMyTechship.Models;

namespace RateMyTechship.Controllers
{
    public class ReviewsController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly UserManager<AppUser> _userManager;

        public ReviewsController(ApplicationDbContext context, UserManager<AppUser> userManager)
        {
            _context = context;
            _userManager = userManager;
        }

        public async Task<IActionResult> MyReviews()
        {
            // Retrieve reviews for the current user
            var currentUser = await _userManager.GetUserAsync(User);
            var userReviews = _context.Review.Where(r => r.AuthorId == currentUser.Id).ToList();
            return View(userReviews);
        }

        // GET: Reviews
        public async Task<IActionResult> Index()
        {
            return View(await _context.Review.ToListAsync());
        }

        //public async Task<IActionResult> Edit(int id, bool like)
        //{
        //    var review = await _context.Review.FindAsync(id);
        //    if (review == null)
        //    {
        //        return NotFound();
        //    }

        //    if (like)
        //    {
        //        review.Likes++;
        //    }
        //    else
        //    {
        //        review.Dislike++;
        //    }

        //    await _context.SaveChangesAsync();

        //    // Return the updated review
        //    return Json(review);
        //}

        [HttpPost]
        [Authorize] // This ensures the user must be logged in
        public async Task<IActionResult> Like(int reviewId)
        {
            var userId = User.FindFirstValue(ClaimTypes.NameIdentifier);
            var review = await _context.Review.FindAsync(reviewId);

            if (review == null)
            {
                return NotFound();
            }

            if (review.LikedByUserIds.Contains(userId))
            {
                review.LikedByUserIds.Remove(userId);
                review.Likes--;
            }
            else
            {

                review.LikedByUserIds.Add(userId);
                review.Likes++;
            }

            _context.SaveChanges();

            return Json(new { success = true, likesCount = review.Likes, likedByCurrentUser = review.HasLiked });
        }

        [HttpPost]
        [Authorize] // This ensures the user must be logged in
        public async Task<IActionResult> Dislike(int reviewId)
        {
            var userId = User.FindFirstValue(ClaimTypes.NameIdentifier);
            var review = await _context.Review.FindAsync(reviewId);

            if (review == null)
            {
                return NotFound();
            }


            if (review.DislikedByUserIds.Contains(userId))
            {
                review.DislikedByUserIds.Remove(userId);
                review.Dislike--;
            }
            else
            {

                review.DislikedByUserIds.Add(userId);
                review.Dislike++;
            }

            _context.SaveChanges();

            return Json(new { success = true, dislikesCount = review.Dislike, dislikedByCurrentUser = review.HasDisliked });
        }

        // GET: Reviews/ShowSearchForm
        public async Task<IActionResult> ShowSearchForm()
        {
            return View(await _context.Review.ToListAsync());
        }

        // POST: Reviews/ShowSearchResults
        public async Task<IActionResult> ShowSearchResults(string SearchPhrase)
        {
            var searchResults = await _context.Review
                .Where(r => r.InternshipReview.Contains(SearchPhrase) ||
                            r.CompanyName.Contains(SearchPhrase) ||
                            r.Position.Contains(SearchPhrase))
                .ToListAsync();

            if (searchResults.Count == 0)
            {
                ViewData["Message"] = "No companies found. Write a review!";
            }
            else
            {
                ViewData["Message"] = ""; // Clear the message if there are search results
            }

            return View("Index", searchResults);
        }

        [Authorize(Roles = "Admin")]
        // GET: Reviews/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var review = await _context.Review
                .FirstOrDefaultAsync(m => m.ID == id);
            if (review == null)
            {
                return NotFound();
            }

            return View(review);
        }

        // GET: Reviews/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Reviews/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("ID,CreationDate,CompanyName,Duration,Position,Rating,InternshipReview,WorkCulture,LearningOpportunities,NetworkingOpportunities,Workload,AuthorId")] Review review)
        {
            if (ModelState.IsValid)
            {
                review.CreationDate = DateTime.Now.ToString("MMMM dd, yyyy");
                if (User.Identity.IsAuthenticated)
                {
                    review.AuthorId = _userManager.GetUserId(User);
                }
                _context.Add(review);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(review);
        }

        // GET: Reviews/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var review = await _context.Review.FindAsync(id);
            if (review == null)
            {
                return NotFound();
            }

            if (!User.Identity.IsAuthenticated || (!User.IsInRole("Admin") && review.AuthorId != _userManager.GetUserId(User)))
            {
                return Forbid(); // Or handle unauthorized access as needed
            }

            return View(review);
        }

        // POST: Reviews/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("ID,CreationDate,CompanyName,Duration,Position,Rating,InternshipReview,WorkCulture,LearningOpportunities,NetworkingOpportunities,Workload")] Review review)
        {
            if (!User.Identity.IsAuthenticated || (!User.IsInRole("Admin") && id != review.ID))
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    var existingReview = await _context.Review.FindAsync(id);
                    if (existingReview == null)
                    {
                        return NotFound();
                    }

                    // Copy the values from the edited review to the existing one,
                    // excluding the Likes and Dislike properties
                    existingReview.CompanyName = review.CompanyName;
                    existingReview.Duration = review.Duration;
                    existingReview.Position = review.Position;
                    existingReview.Rating = review.Rating;
                    existingReview.InternshipReview = review.InternshipReview;
                    existingReview.WorkCulture = review.WorkCulture;
                    existingReview.LearningOpportunities = review.LearningOpportunities;
                    existingReview.NetworkingOpportunities = review.NetworkingOpportunities;
                    existingReview.Workload = review.Workload;

                    // Update the existing review in the database
                    _context.Update(existingReview);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ReviewExists(review.ID))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                //return RedirectToAction(nameof(Index));
                return RedirectToAction(nameof(MyReviews));
            }
            return View(review);
        }



        // POST: Reviews/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        //[HttpPost]
        //[ValidateAntiForgeryToken]
        //public async Task<IActionResult> Edit(int id, [Bind("ID,CreationDate,CompanyName,Duration,Position,Rating,InternshipReview,WorkCulture,LearningOpportunities,NetworkingOpportunities,Workload")] Review review)
        //{
        //    if (id != review.ID)
        //    {
        //        return NotFound();
        //    }

        //    if (ModelState.IsValid)
        //    {
        //        review.CreationDate = DateTime.Now.ToString("MMMM dd, yyyy");
        //        try
        //        {
        //            _context.Update(review);
        //            await _context.SaveChangesAsync();
        //        }
        //        catch (DbUpdateConcurrencyException)

RateMyTechship/Views/Shared/_Layout.cshtml
@* <!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - RateMyTechship</title>
    <link rel="icon" type="image/x-icon" href="/image/Tech.ico" />
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/RateMyTechship.styles.css" asp-append-version="true" />
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css" rel="stylesheet" />
</head> *@
@* <body> *@
    @* <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white" style="height: 75px;">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index" style="font-weight: bold; font-family: Arial Bold, Arial, sans-serif; font-size: 30px;">
                    <span style="color: black; font-weight: bold;">RateMy</span><span style="color: orange; font-weight: bold;">Techship</span>
                </a>
                <a class="btn btn-outline-primary" asp-area="" asp-controller="Home" asp-action="Index" style="color: black; font-weight: bold; font-family: Arial Bold, Arial, sans-serif; font-size: 25px;">Home</a>
                <a class="btn btn-outline-primary" href="/Home#about-us" style="color: black; font-weight: bold; font-family: Arial Bold, Arial, sans-serif; font-size: 25px;">About</a>
                <a class="btn btn-outline-primary" href="/Home#contact" style="color: black; font-weight: bold; font-family: Arial Bold, Arial, sans-serif; font-size: 25px;">Contact</a>

                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                    </ul>
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header> *@
    @* <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white" style="min-height: 75px;">
            <div class="container-fluid d-flex justify-content-between align-items-center">
                <div>
                    <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index" style="font-weight: bold; font-family: Arial Bold, Arial, sans-serif; font-size: 30px;">
                        <span style="color: black; font-weight: bold;">RateMy</span><span style="color: orange; font-weight: bold;">Techship</span>
                    </a>
                </div>
                <div>
                    <a class="btn btn-outline-primary" asp-area="" asp-controller="Home" asp-action="Index" style="color: #777; font-weight: bold; font-family: Arial Bold, Arial, sans-serif; font-size: 25px; border: none;">Home</a>
                    <a class="btn btn-outline-primary" href="/Home#about-us" style="color: #777; font-weight: bold; font-family: Arial Bold, Arial, sans-serif; font-size: 25px; border: none;">About</a>
                    <a class="btn btn-outline-primary" href="/Home#contact" style="color: #777; font-weight: bold; font-family: Arial Bold, Arial, sans-serif; font-size: 25px; border: none;">Contact</a>
                    <a class="btn btn-outline-primary" asp-area="" asp-controller="Reviews" asp-action="Index" style="color: #777; font-weight: bold; font-family: Arial Bold, Arial, sans-serif; font-size: 25px; border: none;">Reviews</a>
                    <a class="btn btn-outline-primary" asp-area="" asp-controller="Internships" asp-action="Index" style="color: #777; font-weight: bold; font-family: Arial Bold, Arial, sans-serif; font-size: 25px; border: none;">Internships</a>
                    <a class="btn btn-outline-primary" asp-area="" asp-controller="Blogs" asp-action="Index" style="color: #777; font-weight: bold; font-family: Arial Bold, Arial, sans-serif; font-size: 25px; border: none;">Blog</a>
                </div>
                <div>
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header> *@

    @* <style>
        /* CSS for button hover effect */
        .btn-outline-primary:hover {
            color: orange !important;
            background-color: transparent !important;
        }
    </style>


    <div class="container body-container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted text-center" style="background-color: orange; color: black;">
        <div class="container" style="color: black">
            &copy; 2024 - RateMyTechship - All Rights Reserved - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a> - <a asp-area="" asp-controller="Home" asp-action="TermsOfUse">Terms of Use</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html> *@

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - RateMyTechship</title>
    <link rel="icon" type="image/x-icon" href="/image/Tech.ico" />
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/RateMyTechship.styles.css" asp-append-version="true" />
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css" rel="stylesheet" />
    <style>

        /* CSS for button hover effect */
        .btn-outline-primary:hover {
            color: orange !important;
            background-color: transparent !important;
        }

        /* The sidebar menu */
        .sidebar {
            height: 100%;
            width: 0;
            position: fixed;
            z-index: 1;
            top: 0;
            left: 0;
            background-color: orange;
            overflow-x: hidden;
            transition: 0.5s;
            padding-top: 60px;
            color: white; /* Ensure the text color is visible against the background */
            border-radius: 7px;
        }

            /* Sidebar links */
            .sidebar a {
                padding: 8px 8px 8px 32px;
                text-decoration: none;
                font-size: 25px;
                color: white;
                display: block;
                transition: 0.3s;
            }

            /* Sidebar close button */
            .sidebar .closebtn {
                position: absolute;
                top: 0;
                right: 25px;
                font-size: 36px;
                margin-left: 50px;
            }

            /* Hover effect for sidebar links */
            .sidebar a:hover {
                color: white;
                background-color: orange;
                font-size: 35px; /* Increase font size on hover */
                border-radius: 5px; /* Rounded corners */
                transform: scale(1.1); /* Scale up the link */
                transition: all 0.3s ease; /* Smooth transition */
                text-decoration: none;
            }


        /* Adjust main content when sidebar is open */
        body.active-sidebar {
            overflow: hidden; /* Prevent scrolling of the main content when sidebar is open */
        }

        /* Ensure the button and logo are aligned properly */
        .navbar-brand {
            display: flex;
            align-items: center;
        }
        #sidebarToggle {
            margin-right: 10px; /* Adjust the spacing as needed */
        }

        .footer-content {
            max-width: 100%;
            overflow: hidden;
        }

        * {
            box-sizing: border-box;
        }
    </style>
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white" style="min-height: 75px;">
            <div class="container-fluid d-flex justify-content-between align-items-center">
                <div class="d-flex align-items-center">
                    <button id="sidebarToggle" class="btn btn-outline-primary" style="color: #777; font-weight: bold; font-family: Arial Bold, Arial, sans-serif; font-size: 25px; border: none; margin-right: 10px;">
                        <i class="fas fa-bars"></i>
                    </button>
                    <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index" style="font-weight: bold; font-family: Arial Bold, Arial, sans-serif; font-size: 30px;">
                        <span style="color: black; font-weight: bold;">RateMy</span><span style="color: orange; font-weight: bold;">Techship</span>
                    </a>
                </div>
                <div>
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>

    <div id="sidebar" class="sidebar">
        <a class="closebtn" href="javascript:void(0)" onclick="closeNav()">&times;</a>
        <a href="/Home">Home</a>
        <a href="/Home#about-us">About</a>
        <a href="/Home#contact">Contact</a>
        <a href="/Reviews">Reviews</a>
        <a href="/Internships">Internships</a>
        <a href="/Blogs">Blog</a>
    </div>

    <div class="container body-container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted text-center" style="background-color: orange; color: black;">
        <div class="footer-content">
        <div class="social-icons" style="margin-bottom: -25px; display: flex; align-items: center; justify-content: center;">
            <span style="font-family: 'Roboto', sans-serif; font-size: 1.5em; color: black; font-weight: bold; margin-right: 10px;">Follow Us</span>
                <a href="https://www.instagram.com/ratemytechship/" target="_blank" style="color: black; font-size: 2em; margin-right: 10px;">
                <i class="fab fa-instagram"></i>
            </a>
                <a href="https://www.tiktok.com/@@ratemytechship?lang=en" target="_blank" style="color: black; font-size: 2em; margin-right: 10px;">
                <i class="fab fa-tiktok"></i>
            </a>
        </div>
        <div class="container" style="color: black; font-size: 13px;">
            &copy; 2024 - RateMyTechship - All Rights Reserved - <a asp-area="" asp-controller="Home" asp-action="Privacy" style="color: black;">Privacy</a> - <a asp-area="" asp-controller="Home" asp-action="TermsOfUse" style="color: black;">Terms of Use</a>
        </div>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script>
        document.getElementById("sidebarToggle").onclick = function () {
            openNav();
        };

        function openNav() {
            document.getElementById("sidebar").style.width = "250px";
            document.body.classList.add("active-sidebar");
        }

        function closeNav() {
            document.getElementById("sidebar").style.width = "0";
            document.body.classList.remove("active-sidebar");
        }
    </script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>